# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 46610efde5b8773adfe8bbb24978ee0e86be3e36e9d0f506a65bc7bbbf43b01077ba36e7af15f4b24b2a0aa98ee905ec0fc0a2cdac4ac79c68cd1dbc96c01d54

test:
  secret_key_base: 6371b570944ace0971922972bc88b9de63a01cc5cfd386ad35032e021c814a80115cd2a1d7a0d5c0f9dea1c19df5979de7c777b6a5e2c6d57ab4b7b552e4325e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
